### ISSUE TITLE
dictionaryToEntity return nil when there is space or dash in PRODUCT_NAME

### ISSUE THREAD

**Issue by cmassi** [Backendless/Swift-SDK#128]
Create a project/target and use a "Display Name" with a space or dash.
Use BackendlessDataCollection to retrieve objects from your Backendless data table.
PersistenceServiceUtils.dictionaryToEntity will return nil, due to NSClassFromString behaviour
To fix the issue in dictionaryToEntity, you could replace any " " or "-" with "_" of resultEntityTypeName string returned by getClassName   

Sample code is already available:
https://github.com/olgadanylova/BackendlessDataCollection
https://backendless.com/backendless-data-collection-tutorial-for-ios/
	https://github.com/Backendless/BackendlessDataCollectionIosSample

Create in Backendless Storage a Person table with a few elements (some with age > 20) 
Run the app and verify that Person table rows are loaded in people collection

In Xcode project replace Display Name "BackendlessDataCollectionSample" with "BackendlessDataCollection Sample" or "BackendlessDataCollection-Sample"

Run the app which will fail in subscript

public subscript (position: Int) -> Identifiable {

        return backendlessCollection[position]	-> Thread 1: Fatal error: Index out of range
    }

The issue is in empty backendlessCollection, even if count is correct, because self.loadNextPage() does not find the Person class 
The tableView expect people?.count objects to be loaded in PersonCell, according to the correct number returned by dataStore.getObjectCount, but as soon as people?[indexPath.row] is executed, subscript fails because backendlessCollection is empty

To make BackendlessDataCollectionSample more stable, I would use

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {

        guard let people = self.people else { return 0 }
        return people.isLoaded() ? people.count : 0

    }

    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "PersonCell", for: indexPath)

        guard let people = self.people else {return cell}

        if people.isLoaded() {
            if let person = people[indexPath.row] as? Person {
                cell.textLabel?.text = "\(person.name ?? "NoName"), age: \(person.age)"
            }
        }
        return cell
    }

To fix the issue, should modify BackendlessSwift pod in PersistenceServiceUtils class.
You could replace in dictionaryToEntity any " " or "-" with "_" of resultEntityTypeName string returned by getClassName 

See details of executed methods:

BackendlessDataCollection.swift

    public subscript (position: Int) -> Identifiable {
	...
            self.loadNextPage()
	...
        return backendlessCollection[position]
    }

    private func loadNextPage() {

        dataStore.find(queryBuilder: queryBuilder, responseHandler: { [weak self] foundObjects in
	...
            guard let foundObjects = foundObjects as? [Identifiable] else {
                semaphore.signal()
                return
            }
            self.backendlessCollection += foundObjects
            offset += foundObjects.count
	...
    }

DataStoreFactory.swift

    public func find(queryBuilder: DataQueryBuilder, responseHandler: (([Any]) -> Void)!, errorHandler: ((Fault) -> Void)!) {
	...
            for responseObject in responseArray {
                if let resultObject = self.persistenceServiceUtils.dictionaryToEntity(dictionary: responseObject, className: self.persistenceServiceUtils.getClassName(entity: self.entityClass)) {
                    resultArray.append(resultObject)
                }
	...
    }

PersistenceServiceUtils.swift

    func dictionaryToEntity(dictionary: [String: Any], className: String) -> Any? {

    ...
        var resultEntityTypeName = className
        let classMappings = mappings.getTableToClassMappings()
        if classMappings.keys.contains(className) {
            resultEntityTypeName = classMappings[className]!
        }
        resultEntityTypeName = resultEntityTypeName.replacingOccurrences(of: "-", with: "_")
        var resultEntityType = NSClassFromString(resultEntityTypeName) as? NSObject.Type
        if resultEntityType == nil {
            resultEntityTypeName = getClassName(className: resultEntityTypeName)
            resultEntityType = NSClassFromString(resultEntityTypeName) as? NSObject.Type
        }
        if resultEntityType == nil {
            resultEntityTypeName = resultEntityTypeName.components(separatedBy: ".").last!
            resultEntityType = NSClassFromString(resultEntityTypeName) as? NSObject.Type
        }
        if resultEntityType == nil {
            resultEntityTypeName = "SwiftSDK." + resultEntityTypeName
            resultEntityType = NSClassFromString(resultEntityTypeName) as? NSObject.Type
        }
        if let resultEntityType = resultEntityType {
        ...        }
        return nil
    }

With a breakpoint in dictionaryToEntity after getClassName, we see that entity is nil:

resultEntityTypeName	String	"BackendlessDataCollection Sample.Person"	
resultEntityType	(@thick NSObject.Type)?	nil	none

or

resultEntityTypeName	String	"BackendlessDataCollection-Sample.Person"	
resultEntityType	(@thick NSObject.Type)?	nil	none

When there is no space in app Display Name the entity is not nil

resultEntityTypeName	String	"BackendlessDataCollectionSample.Person"	
resultEntityType	(@thick NSObject.Type)?	BackendlessDataCollectionSample.Person	0x0000000109748a78

I would replace " " and "-" with "_"

        if resultEntityType == nil {
            resultEntityTypeName = getClassName(className: resultEntityTypeName)
            resultEntityTypeName = resultEntityTypeName.replacingOccurrences(of: " ", with: "_").replacingOccurrences(of: "-", with: "_")
            resultEntityType = NSClassFromString(resultEntityTypeName) as? NSObject.Type
        }

**Comment by cmassi** [comment]
By default when we set  "Display Name"  in Xcode -> General -> Identity, we define the PRODUCT_NAME, which is used for both "Bundle Name" and "Bundle Display Name".

As a workaround for the issue of dictionaryToEntity, we can add in Info.plist, a distinct value for the "Bundle Display Name", which is the key CFBundleDisplayName

1) As soon as we add this key, it is by default the same as "Bundle Name", which is $PRODUCT_NAME

	<key>CFBundleDisplayName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>

2) Now we have to set a value for PRODUCT_NAME without space/dash.
In Xcode -> General -> Identity set the "Display Name" as BackendlessDataCollectionSample , 
In Build Settings we can verify that PRODUCT_NAME has a value without space/dash, and PRODUCT_MODULE_NAME has a value without "_".

3) Then in Info.plist we edit the CFBundleDisplayName and replace $(PRODUCT_NAME) with any string, even with space/dash, like "BackendlessDataCollection Sample".

Because getClassName uses the kCFBundleNameKey which is PRODUCT_NAME, the NSClassFromString will be able to find the Person type, and dictionaryToEntity will not return nil

**Comment by olgadanylova** [comment]
Hello @cmassi,
The internal ticket BKNDLSS-19867 created. 
We'll investigate this issue as soon as possible

**Comment by olgadanylova** [comment]
Issue has been fixed. Please update to the version 5.5.9
