### ISSUE TITLE
SPM support?

### ISSUE THREAD

**Issue by liweihan** [Backendless/Swift-SDK#171]
Hello,

Thanks for keeping up the great work! The only dependency socketIO has support SPM, would be great to have this SDK support SPM as well. With my current setup Backendless is the one that hasn't support it yet.

https://github.com/socketio/socket.io-client-swift/blob/master/Package.swift

**Comment by olgadanylova** [comment]
Hello @liweihan,
Thanks for your response! We'll discuss adding SPM in Swift-SDK on our roadmap as soon as possible.
I've created an internal ticket BKNDLSS-22487 for it.

Regards,
Olha

**Comment by olgadanylova** [comment]
SPM support added in v6.0.3. Could you please check and verify whether it works fine?

Regards,
Olha
