### ISSUE TITLE
'SocketEngine' does not conform to protocol 'WebSocketDelegate'

### ISSUE THREAD

**Issue by alancook** [Backendless/Swift-SDK#254]
Updating to Backendless causes a problem with the Sockets which is required by the package https://github.com/socketio/socket.io-client-swift, error is 'SocketEngine' does not conform to protocol 'WebSocketDelegate'

**Comment by alancook** [comment]
The work around Solution was to make the SocketEngine.swift file editable and edit it in TextEdit and add the required Protocol, but this should be add to the SocketIO repository

    public func didReceive(event: Starscream.WebSocketEvent, client: Starscream.WebSocketClient) {
        
    }

**Comment by olha-danylova** [comment]
Hello @alancook,

Could you please provide more information? What Xcode and Backendless versions do you use?

**Comment by olha-danylova** [comment]
https://support.backendless.com/t/socketengine-does-not-conform-to-protocol-websocketdelegate/17179
